# Add files and commands to this file, like the example:
#   watch(%r{file/path}) { `command(s)` }
#

guard 'shell' do
  watch(%r{(.+)\.tex}) do |m|
    `pdflatex -interaction=batchmode #{m[0]} >/dev/null`
  end
end
