CFLAGS += -O2 -g -W -Wall -std=c99
#-Wsign-compare -Wfloat-equal -Wformat-security #-Werror
CPPFLAGS +=
LDFLAGS +=

all: game

game: graphics.o

clean:
	-rm -f game

install:

.PHONY: all install clean
