#
# Simple development makefile
#

#
# add more flags here,
# but don't remove the "+="
#
CFLAGS += -O2 -g -W -Wall -Werror -std=c99
#-Wsign-compare -Wfloat-equal -Wformat-security #-Werror
CPPFLAGS +=
LDFLAGS +=

all: game

clean:
	-rm -f game

install:

play:
	make
	./game

.PHONY: all install clean

# end of development makefile
